### ISSUE TITLE
Protect against man-in-the-middle attacks (GPG signature checking, HTTPs)

### ISSUE THREAD

**Issue by hartwork** [tokland/arch-bootstrap#13]
Hi!

There seems to be no checking of GPG signatures and the URLs used internally start with http:// rather than https:// (while at least http://mirrors.kernel.org/archlinux could be replaced by https://mirrors.kernel.org/archlinux). That leaves quite some surface for man-in-the-middle attacks.

I propose to download GPG keys through HTTPs and check GPG signatures of packages downloaded.

Thanks and best, Sebastian

**Comment by tokland** [comment]
Good points. Changed to https (69f47a6f). As for the GPG checking, I'll accept pull request for that feature. Thanks!

**Comment by hartwork** [comment]
Re-opening for 0ea1af983445ca0062135a4dcfca6920fe09953e.

**Comment by tokland** [comment]
8a6d28ff
