### ISSUE TITLE
use the download directory as cache

### ISSUE THREAD

**Issue by yannayl** [tokland/arch-bootstrap#18]
when using the `'-d <download_dir>'` option, do not download the files which are already in the directory.

perhaps we should verify them with a hash or something.

improvement: let pacman also know about those packages.

**Comment by gevans** [comment]
Right. IIRC, wget compares timestamps when files already exist. Since wget was replaced with curl, a fix might be using `curl -z` to reenable that functionality.

**Comment by tokland** [comment]
done: 36669b55
