### ISSUE TITLE
Download directory is no longer preserved

### ISSUE THREAD

**Issue by gevans** [tokland/arch-bootstrap#19]
Previously, arch-bootstrap saved packages and *kept* them between runs when a user-specified directory was passed through the `-d` flag. It looks like 0a66940b2027ca6328bb2dc2e73ffdf23747f28a removed this functionality resulting in user-specified directories being [completely wiped out at exit](https://github.com/tokland/arch-bootstrap/blob/0a66940b2027ca6328bb2dc2e73ffdf23747f28a/arch-bootstrap.sh#L185).

**Comment by tokland** [comment]
I have no idea why I removed that, it's indeed a nice feature to have.

**Comment by tokland** [comment]
2b3ebe11 sorry for the delay.
