### ISSUE TITLE
Process does not create .arch-chroot in root dir

### ISSUE THREAD

**Issue by mdeguzis** [tokland/arch-bootstrap#27]
It is odd that this wrapper does not  rwatw the chroot in the structure that this page describes: https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot

This then doesn't allow makechrootpkg to run, as it checks for dir/. arch-chroot under dir/root. Why doesn't this script house the root contents in root/ not the directory passed to it? Where is .arch-chroot?

Contents of . arch-chroot

```
v4
```

That is an old 85th chroot I have. 

arch-nspawn where the check occurs: http://sprunge.us/KAZj

Is the wiki outdated for Arch and I should not be using makechrootpkg?

**Comment by tokland** [comment]
@mdeguzis I don't have time to look into this, if you are able to fix it to meet your needs and send a PR, I'll merge it.
