### ISSUE TITLE
Fails, when the path has a blank.

### ISSUE THREAD

**Issue by redtrumpet** [tokland/arch-bootstrap#28]
I tried this with

    jonas@jonas-elementary:~$ sudo arch-bootstrap -a x86_64 /media/jonas/Arch\ Linux/

but it failed here:

    --- download package: http://mirrors.kernel.org/archlinux/core/os/x86_64/filesystem-2017.03-2-x86_64.pkg.tar.xz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 10448  100 10448    0     0  22190      0 --:--:-- --:--:-- --:--:-- 22182
    --- uncompress package: /tmp/tmp.n2vsN9Jh0K/filesystem-2017.03-2-x86_64.pkg.tar.xz
    --- configure DNS and pacman
    sed: kann /media/jonas/Arch nicht lesen: Datei oder Verzeichnis nicht gefunden
    sed: kann Linux//etc/shadow nicht lesen: Datei oder Verzeichnis nicht gefunden

**Comment by tokland** [comment]
Fixed by 5a7240f
