### ISSUE TITLE
What does -q installation flag does?

### ISSUE THREAD

**Issue by arthurmoises** [tokland/arch-bootstrap#33]
arthur@arthur-K46CB:/$ ./arch-bootstrap.sh 
Usage: arch-bootstrap.sh [-q] [-a i686|x86_64|arm] [-r REPO_URL] [-d DOWNLOAD_DIR] DESTDIR

**Comment by tokland** [comment]
It configures static qemu. PR from a user that needed it:

https://github.com/tokland/arch-bootstrap/blob/master/arch-bootstrap.sh#L180

https://github.com/tokland/arch-bootstrap/pull/10
