### ISSUE TITLE
NO ARM POSSIBLE !!!

### ISSUE THREAD

**Issue by cheznewa** [tokland/arch-bootstrap#55]
I Cannot Use This On My Raspberry Pi !! So Please Fix The Problem Yourself Instead Waiting A Pull Request !!! ù$%!=

**Comment by yannayl** [comment]
This is an open source project. And nobody owes you nothing. Do it yourself the same way I did 5 years ago.

If you don't contribute to the collaborative effort, the least you can do is not to be rude.
