### ISSUE TITLE
Does it work with a Linux distro?

### ISSUE THREAD

**Issue by Melechtna** [tokland/arch-bootstrap#60]
Not sure what a GNU distro is since GNU is a toolset that tends to make up less that 5% of any system it's on, does it work with a Linux Distro?

**Comment by cromerc** [comment]
Linux is not an operating system, it is a kernel. The operating system in question is called GNU.

Ubuntu is GNU OS, Arch Linux is a GNU OS, Debian is a GNU OS, Fedora is a GNU OS.

Alpine does NOT have GNU, but does have the linux kernel.

So obviously it works on Ubuntu, Arch Linux, Debian, and Fedora which are all GNU/Linux distros.

However alpine which does have the linux kernel, doesn't have GNU and probably will not work or could have bugs.

**Comment by Melechtna** [comment]
> Linux is not an operating system, it is a kernel. The operating system in question is called GNU.
> 
> Ubuntu is a GNU OS, Arch Linux is a GNU OS, Debian is a GNU OS, Fedora is a GNU OS.
> 
> Alpine does NOT have GNU, but does have the linux kernel.
> 
> So obviously it works on Ubuntu, Arch Linux, Debian, and Fedora which are all GNU/Linux distros.
> 
> However alpine which does have the linux kernel, doesn't have GNU and probably will not work or could have bugs.

https://media.tenor.com/9X87EErUHJcAAAAC/that-is-false-spider-man.gif
